// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // migrate/db/studio butuh koneksi langsung, bukan pooled pgbouncer.
    // Runtime app tetap pakai DATABASE_URL lewat adapter di src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
